import Head from 'next/head'
import Header from '../components/Header'
import Title from '../components/Title'
import Buttons from '../components/Buttons'
import Gator from '../components/Gator'
import BgSVG from '../components/BgSVG'
import Skills from '../components/Skills'
import WorkSection from '../components/WorkSection'
// import Image from 'next/image'
// import BGSVG from '../../public/bg.svg'

export default function Home () {
  return (
    <div className='bg-portfolio min-h-screen text-white'>
      <Head>
        <title>Home | LKY </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@900&display=swap" rel="stylesheet" />
      </Head>
      <Header />
      <div className='flex items-center z-20 justify-center'>
        <div className='mx-20 my-32'>
          <Title />
          <Buttons />
        </div>
        <Gator />
      </div>
      <Skills />
      <WorkSection />
      {/* <BgSVG /> */}
    </div>
  )
}
